### ISSUE TITLE
Design Mockup

### ISSUE THREAD

**Issue by EliasJorgensen** [Entake/acuity#1]
We need to create a mockup for the design, that we are intending to pursue.
The mockup does not have to specify the design for ever possible edge case, just a general theme for the site, and mockup designs for the tasks that the user are going to do the most, eg:
- Landing Page
- Login / Account creation
- Image upload/sharing
- Image search (and filters maybe)

It does not need to be pixel perfect, as it's just a mockup to get started from.
The quicker it's done, the faster we can hit the _Start Development_ milestone.

**Comment by AkselNLadegaard** [comment]
Mostly done. We'll see it today whilst I continue work on the missing elements. There's plenty to start off with though

**Comment by EliasJorgensen** [comment]
Has been created, although not a part of the git repo.
Marking as closed.
